language: python
python:
#  - "3.3"
  - "2.7"

env:
  - ROOT=5.34.05
  - ROOT=5.32.04

virtualenv:
  system_site_packages: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # Needed because sometimes travis' repositories get out of date
  - time sudo apt-get update -qq
  # Install the dependencies we need
  - time sudo apt-get install -qq python${PYTHON_SUFFIX}-numpy python${PYTHON_SUFFIX}-sphinx python${PYTHON_SUFFIX}-nose python${PYTHON_SUFFIX}-numexpr python${PYTHON_SUFFIX}-scipy
  - pip install numexpr
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-pep8
  # Install a ROOT binary that we custom-built in a 64-bit Ubuntu VM
  # for the correct Python / ROOT version
  - time wget --no-check-certificate https://dl.dropbox.com/u/4923986/rootpy/64/root_v${ROOT}_Python_${TRAVIS_PYTHON_VERSION}.tar.gz
  - time tar zxf root_v${ROOT}_Python_${TRAVIS_PYTHON_VERSION}.tar.gz
  - source root_v${ROOT}_Python_${TRAVIS_PYTHON_VERSION}/bin/thisroot.sh
before_script:
  - py.test --cov=bad
script:

  # Check if root and PyROOT work ok
  - time root -l -b -q
  - time python -c 'import ROOT; ROOT.TBrowser()'

  # Run tests
  - py.test tests -v --cov bad --cov-report term-missing --pep8 bad

after_success:
    - coveralls